version: '3.7'
services:
  rails-example:
    build:
      context: .
    image: docker-examples/rails-example
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    stdin_open: true
    tty: true 
